// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/app.proto

package service_metadata_app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_3850787927b6c91f, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Module struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	AppId                string   `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ParentModuleId       string   `protobuf:"bytes,5,opt,name=parent_module_id,json=parentModuleId,proto3" json:"parent_module_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_3850787927b6c91f, []int{1}
}

func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Module) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Module) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Module) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Module) GetParentModuleId() string {
	if m != nil {
		return m.ParentModuleId
	}
	return ""
}

type Form struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Detail               string   `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	AppId                string   `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ModuleId             string   `protobuf:"bytes,6,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Form) Reset()         { *m = Form{} }
func (m *Form) String() string { return proto.CompactTextString(m) }
func (*Form) ProtoMessage()    {}
func (*Form) Descriptor() ([]byte, []int) {
	return fileDescriptor_3850787927b6c91f, []int{2}
}

func (m *Form) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Form.Unmarshal(m, b)
}
func (m *Form) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Form.Marshal(b, m, deterministic)
}
func (m *Form) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Form.Merge(m, src)
}
func (m *Form) XXX_Size() int {
	return xxx_messageInfo_Form.Size(m)
}
func (m *Form) XXX_DiscardUnknown() {
	xxx_messageInfo_Form.DiscardUnknown(m)
}

var xxx_messageInfo_Form proto.InternalMessageInfo

func (m *Form) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Form) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Form) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Form) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Form) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Form) GetModuleId() string {
	if m != nil {
		return m.ModuleId
	}
	return ""
}

type Response struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3850787927b6c91f, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AppResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	App                  *App     `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppResponse) Reset()         { *m = AppResponse{} }
func (m *AppResponse) String() string { return proto.CompactTextString(m) }
func (*AppResponse) ProtoMessage()    {}
func (*AppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3850787927b6c91f, []int{4}
}

func (m *AppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppResponse.Unmarshal(m, b)
}
func (m *AppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppResponse.Marshal(b, m, deterministic)
}
func (m *AppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppResponse.Merge(m, src)
}
func (m *AppResponse) XXX_Size() int {
	return xxx_messageInfo_AppResponse.Size(m)
}
func (m *AppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppResponse proto.InternalMessageInfo

func (m *AppResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *AppResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AppResponse) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type ModuleResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Module               *Module  `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleResponse) Reset()         { *m = ModuleResponse{} }
func (m *ModuleResponse) String() string { return proto.CompactTextString(m) }
func (*ModuleResponse) ProtoMessage()    {}
func (*ModuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3850787927b6c91f, []int{5}
}

func (m *ModuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleResponse.Unmarshal(m, b)
}
func (m *ModuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleResponse.Marshal(b, m, deterministic)
}
func (m *ModuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleResponse.Merge(m, src)
}
func (m *ModuleResponse) XXX_Size() int {
	return xxx_messageInfo_ModuleResponse.Size(m)
}
func (m *ModuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleResponse proto.InternalMessageInfo

func (m *ModuleResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *ModuleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ModuleResponse) GetModule() *Module {
	if m != nil {
		return m.Module
	}
	return nil
}

type FormResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Form                 *Form    `protobuf:"bytes,3,opt,name=form,proto3" json:"form,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormResponse) Reset()         { *m = FormResponse{} }
func (m *FormResponse) String() string { return proto.CompactTextString(m) }
func (*FormResponse) ProtoMessage()    {}
func (*FormResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3850787927b6c91f, []int{6}
}

func (m *FormResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormResponse.Unmarshal(m, b)
}
func (m *FormResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormResponse.Marshal(b, m, deterministic)
}
func (m *FormResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormResponse.Merge(m, src)
}
func (m *FormResponse) XXX_Size() int {
	return xxx_messageInfo_FormResponse.Size(m)
}
func (m *FormResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FormResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FormResponse proto.InternalMessageInfo

func (m *FormResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *FormResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FormResponse) GetForm() *Form {
	if m != nil {
		return m.Form
	}
	return nil
}

func init() {
	proto.RegisterType((*App)(nil), "service.metadata.app.App")
	proto.RegisterType((*Module)(nil), "service.metadata.app.Module")
	proto.RegisterType((*Form)(nil), "service.metadata.app.Form")
	proto.RegisterType((*Response)(nil), "service.metadata.app.Response")
	proto.RegisterType((*AppResponse)(nil), "service.metadata.app.AppResponse")
	proto.RegisterType((*ModuleResponse)(nil), "service.metadata.app.ModuleResponse")
	proto.RegisterType((*FormResponse)(nil), "service.metadata.app.FormResponse")
}

func init() { proto.RegisterFile("app/app.proto", fileDescriptor_3850787927b6c91f) }

var fileDescriptor_3850787927b6c91f = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0x91, 0x25, 0xcb, 0xf2, 0xb8, 0x35, 0x65, 0x69, 0x8b, 0xea, 0x96, 0xd2, 0x8a, 0x1e,
	0x0c, 0x05, 0x05, 0x9c, 0x1c, 0x93, 0x83, 0x21, 0xd8, 0x38, 0x10, 0x02, 0xf6, 0x03, 0x98, 0x4d,
	0x76, 0x12, 0x04, 0x92, 0x35, 0x48, 0x6b, 0xe3, 0x6b, 0xae, 0x79, 0xb4, 0x3c, 0x55, 0xd8, 0xd5,
	0x2a, 0xf6, 0x41, 0x96, 0x82, 0x7d, 0xdb, 0x9d, 0xfd, 0xf9, 0xff, 0x6f, 0x67, 0xb4, 0x82, 0xcf,
	0x9c, 0xe8, 0x8c, 0x13, 0x85, 0x94, 0xa5, 0x32, 0x65, 0x5f, 0x73, 0xcc, 0x36, 0xd1, 0x03, 0x86,
	0x09, 0x4a, 0x2e, 0xb8, 0xe4, 0x21, 0x27, 0x0a, 0xae, 0xc0, 0x1e, 0x13, 0xb1, 0x3e, 0xb4, 0x22,
	0xe1, 0x5b, 0x7f, 0xac, 0x61, 0x77, 0xde, 0x8a, 0x04, 0x63, 0xe0, 0xac, 0x78, 0x82, 0x7e, 0x4b,
	0x57, 0xf4, 0x5a, 0xd5, 0x24, 0x6e, 0xa5, 0x6f, 0x17, 0x35, 0xb5, 0x0e, 0x9e, 0x2d, 0x70, 0x6f,
	0x53, 0xb1, 0x8e, 0xf1, 0x58, 0x0b, 0xf6, 0x0d, 0x5c, 0x4e, 0xb4, 0x8c, 0x84, 0xef, 0xe8, 0x6a,
	0x9b, 0x13, 0xcd, 0x04, 0x1b, 0xc2, 0x17, 0xe2, 0x19, 0xae, 0xe4, 0x32, 0xd1, 0xfe, 0x4a, 0xd0,
	0xd6, 0x82, 0x7e, 0x51, 0x2f, 0x62, 0x67, 0x22, 0x78, 0xb1, 0xc0, 0x99, 0xa4, 0x59, 0x72, 0x34,
	0xc1, 0x77, 0x70, 0x05, 0x4a, 0x1e, 0xc5, 0x86, 0xc0, 0xec, 0xf6, 0xc8, 0xda, 0xfb, 0x64, 0x3f,
	0xa1, 0xbb, 0x43, 0x72, 0xf5, 0x89, 0x97, 0x94, 0x30, 0x97, 0xe0, 0xcd, 0x31, 0xa7, 0x74, 0x95,
	0xa3, 0xf2, 0xcd, 0x30, 0x5f, 0xc7, 0x52, 0x33, 0x79, 0x73, 0xb3, 0x63, 0x3e, 0x74, 0x12, 0xcc,
	0x73, 0xfe, 0x54, 0xa2, 0x95, 0xdb, 0x20, 0x86, 0xde, 0x98, 0xe8, 0x78, 0x03, 0xf6, 0x1f, 0x6c,
	0x4e, 0xa4, 0x6f, 0xd7, 0x1b, 0xfd, 0x08, 0xab, 0x46, 0x1e, 0xaa, 0x04, 0xa5, 0x0a, 0xb6, 0xd0,
	0x2f, 0x9a, 0x78, 0x42, 0xe0, 0x05, 0xb8, 0xc5, 0xdd, 0x4d, 0xe6, 0xaf, 0xea, 0x4c, 0x93, 0x63,
	0xb4, 0x01, 0xc1, 0x27, 0x35, 0xb1, 0x13, 0x72, 0x43, 0x70, 0x1e, 0xd3, 0x2c, 0x31, 0xa9, 0x83,
	0xea, 0x54, 0x9d, 0xa1, 0x75, 0xa3, 0x57, 0x1b, 0x60, 0x4c, 0xb4, 0x28, 0x64, 0xec, 0x1a, 0x3a,
	0x0b, 0xbe, 0x41, 0xf5, 0xe9, 0x1f, 0xee, 0xd2, 0xe0, 0x77, 0xf5, 0xd1, 0x3b, 0xf6, 0x04, 0xdc,
	0x29, 0xca, 0x06, 0x93, 0xbf, 0x87, 0xa7, 0x50, 0xfa, 0xdc, 0x00, 0x28, 0x1a, 0xf3, 0x90, 0x6a,
	0x5b, 0xd8, 0xc8, 0x74, 0x07, 0xdd, 0x29, 0xca, 0x0f, 0x59, 0xfd, 0xab, 0x9d, 0xd5, 0xee, 0x92,
	0x9e, 0x82, 0xd3, 0x2f, 0xac, 0xa6, 0xcf, 0x8d, 0x60, 0x33, 0xe8, 0x4c, 0x51, 0x36, 0xda, 0x04,
	0x35, 0xa3, 0x34, 0x56, 0xf7, 0xae, 0xfe, 0xa3, 0x9d, 0xbf, 0x05, 0x00, 0x00, 0xff, 0xff, 0x67,
	0xfc, 0x3a, 0x5e, 0xe2, 0x04, 0x00, 0x00,
}
